Update to match MobSF
Optimize order of ops

Fix firebase_analysis TypeError issue

TypeError: not all arguments converted during string formatting

Add missing code to template

Remove errant endif

Remove another {% endif %} tag

Add logic to ensure context is complete

Remove debugging to make lint happy

Fix YALE (Yet Another Lint Error)